import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { Roboto } from "next/font/google";
import type { Metadata } from "next";
import LeftSideBar from "@/components/shared/LeftSideBar";
import "../globals.css";
import StreamVideoProvider from "@/providers/StreamClientProvider";
import "@stream-io/video-react-sdk/dist/css/styles.css";
const roboto = Roboto({ subsets: ["latin"], weight: ["500"] });

export const metadata: Metadata = {
  title: "Social Media",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <AppRouterCacheProvider>
          <StreamVideoProvider>
            <main className="flex flex-row">
              <LeftSideBar />
              {children}
            </main>
          </StreamVideoProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
