import {
  HomeOutlined,
  HomeRounded,
  SearchOutlined,
  SearchRounded,
  ExploreOutlined,
  ExploreRounded,
  VideoLibraryOutlined,
  VideoLibraryRounded,
  NearMeOutlined,
  NearMeRounded,
  FavoriteBorderOutlined,
  FavoriteBorderRounded,
  PeopleAltOutlined,
  PeopleAltRounded,
} from "@mui/icons-material";

export const sideBarItems = [
  {
    id: 1,
    iconNonActive: <HomeOutlined />,
    iconActive: <HomeRounded />,
    route: "/",
    label: "Home",
  },
  {
    id: 2,
    iconNonActive: <SearchOutlined />,
    iconActive: <SearchRounded />,
    route: "",
    label: "Search",
  },
  {
    id: 3,
    iconNonActive: <ExploreOutlined />,
    iconActive: <ExploreRounded />,
    route: "/explore",
    label: "Explore",
  },
  {
    id: 4,
    iconNonActive: <VideoLibraryOutlined />,
    iconActive: <VideoLibraryRounded />,
    route: "/reels",
    label: "Reels",
  },
  {
    id: 5,
    iconNonActive: <NearMeOutlined />,
    iconActive: <NearMeRounded />,
    route: "/messages",
    label: "Messages",
  },
  {
    id: 6,
    iconNonActive: <FavoriteBorderOutlined />,
    iconActive: <FavoriteBorderRounded />,
    route: "",
    label: "Notifications",
  },
  {
    id: 7,
    iconNonActive: <PeopleAltOutlined />,
    iconActive: <PeopleAltRounded />,
    route: "/friends",
    label: "Friends",
  },
];
