export const QueryKeys = {
    GET_POST_LIST: "GET_COURT_LIST",
    GET_COMMENT_LIST: "GET_COMMENT_LIST",
    GET_POST_VIEWER: "GET_POST_VIEWER",
    GET_COMMENT_REACTION: "GET_COMMENT_REACTION",
  };